FROM node:16-alpine

WORKDIR /app

COPY public public
COPY src src
COPY package-lock.json package-lock.json
COPY package.json package.json
COPY README.md README.md
COPY tsconfig.json tsconfig.json

RUN npm ci

CMD ["npm", "start"]

#docker build -t build2022/web:latest -f dockerfile .