FROM python:3.10-slim-buster

COPY ./db ./db

WORKDIR ./python

COPY ./python/main.py main.py

COPY ./python/images images

COPY ./python/requirements.txt requirements.txt
RUN pip install -r requirements.txt


# STEP4-4では以下は変更しない
# CMD ["python", "-V"]

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "9000"]